### ISSUE TITLE
No Such Element Exception

### ISSUE THREAD

**Issue by iopsych** [MatthewChatham/glassdoor-review-scraper#17]
Hi there...

I am also getting a no such element exception.  Mine is slightly different than what NKoenig06 reported in that it is "Unable to locate element: {"method": "css selector", "selector":".reviewBodyCell"}

I've tinkered around but can't seem to fix it.

**Comment by BiggerSplash** [comment]
Same here ... I guess Glassdoor changed parts of the CSS structure...

**Comment by hannahewha** [comment]
same here

**Comment by hannahewha** [comment]
Can some one help?

**Comment by nush12** [comment]
same issue :-|

**Comment by tsp2123** [comment]
hi, just change 'reviewbodycell' to 'hreview' that's the new class name they're using. Alongside this issue you may have trouble with the navigation buttons. I'm just tinkering with Matt's code to see if I can get everything updated. I'll post when I'm done. If someone is more speedy, please share.

**Comment by iopsych** [comment]
Admittedly - I know nothing about Python, but I spent some time with it and got it all working.  It required quite a bit of changes to the paging, the show more button, and a few other things using Xpath and Css selector code.  

I'm also a big newbie to using Github.  But I uploaded the code under my repository.  Apologies if this wasn't the right way to do this.

**Comment by tsp2123** [comment]
@iopsych  do you find that your working code fucks up at any point? I sometimes have an issue where the scraper can run for about 15,000 reviews before I get a no such element exception. Even though, I've revised the paging, etc. and it was working before

**Comment by iopsych** [comment]
@tsp2123 - I haven't run it for any large companies with so many ratings.  I will give it a shot and see how it goes.

**Comment by SleepyGinger** [comment]
@iopsych thanks for the code! it works like a charm! last day at my job and possibly the last thing they asked from me and i delivered!!!

**Comment by tpathrikatu** [comment]
when trying to run the code in the pros cons and advice to management cells I am getting: "Nam quis nulla. Integer malesuada. In in enim a arcu imperdiet."

**Comment by jhatamyar** [comment]
@iopsych THANK YOU you are a lifesaver!! @tsp2123 I will keep this thread posted if I run into the issue you are having.

**Comment by Titus7777** [comment]
@iopsych Thank you for fixing and posting the revised code.  It works well except when it encounters the issue identified by @tsp2123 where scrapes on firms with larger numbers of reviews will capture hundreds of pages of reviews successfully and then terminate without saving after hitting a no such element error.  The error results from Glassdoor's Cloudflare DDoS protection popping up a dialog with a "Click here to reload." prompt which the script isn't programmed to recognize and respond to.

**Comment by hanhan0123** [comment]
@iopsych  Fixed problem I had. Thanks! But see different issue. Same as what others mentioned. It seems like it is not going to next page after 9 for me. I see reviews in page 8 in Glassdoor however it says Found 0 reviews on page 8. Also, I put --limit 500, but does it scraping more than 500? cuz 10*7 =700? scraped at least 700? 

By the way, please let me know if you got to fix the code! or anyone let me know how should I do if I want to college what I scraped so far. 

2019-08-13 14:11:48,855 INFO 294    :main1.py(21321) - Scraped data for "Great Company"(Thu Aug 09 2018 09:04:16 GMT-0400 (Eastern Daylight Time))
2019-08-13 14:11:48,889 INFO 318    :main1.py(21321) - Going to page 8
2019-08-13 14:12:01,043 INFO 283    :main1.py(21321) - Extracting reviews from page 8
2019-08-13 14:12:01,070 INFO 288    :main1.py(21321) - Found 0 reviews on page 8
2019-08-13 14:12:01,108 INFO 318    :main1.py(21321) - Going to page 9
Traceback (most recent call last):
  File "main1.py", line 454, in <module>
    main()
  File "main1.py", line 442, in main
    go_to_next_page()
  File "main1.py", line 319, in go_to_next_page
    next_ = browser.find_element_by_xpath(".//li[@class='pagination__PaginationStyle__next']/a")
  File "//anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "//anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "//anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "//anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":".//li[@class='pagination__PaginationStyle__next']/a"}
  (Session info: headless chrome=76.0.3809.100)
