### ISSUE TITLE
Gets first 10 reviews then I get this error

### ISSUE THREAD

**Issue by LioGabriella** [MatthewChatham/glassdoor-review-scraper#23]
Traceback (most recent call last):
  File "main.py", line 461, in <module>
    main()
  File "main.py", line 446, in main
    while more_pages() and\
  File "main.py", line 314, in more_pages
    paging_control = browser.find_element_by_class_name('pagingControls')
  File "C:\Users\GLio\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\GLio\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\GLio\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\GLio\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".pagingControls"}
  (Session info: headless chrome=76.0.3809.132)

**Comment by LioGabriella** [comment]
Found answer in: https://github.com/MatthewChatham/glassdoor-review-scraper/issues/14 ..was able to fix the issue thank you
