### ISSUE TITLE
version of ChromeDriver only supports Chrome version 78  But my chrome version is 78

### ISSUE THREAD

**Issue by wenxin-lab** [MatthewChatham/glassdoor-review-scraper#28]
Hi, I tried the code, and got this error:

2019-09-29 15:41:04,215 INFO 377 :main.py(10918) - Configuring browser
Traceback (most recent call last):
File "main.py", line 412, in
browser = get_browser()
File "main.py", line 382, in get_browser
browser = wd.Chrome(options=chrome_options)
File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in init
desired_capabilities=desired_capabilities)
File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in init
self.start_session(capabilities, browser_profile)
File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
response = self.execute(Command.NEW_SESSION, parameters)
File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78

But my chrome version is 78, so I have no idea how to fix it...

**Comment by wenxin-lab** [comment]
I fixed that, I change the chromedrive to 77 to match my chrome
