### ISSUE TITLE
No such element error

### ISSUE THREAD

**Issue by wenxin-lab** [MatthewChatham/glassdoor-review-scraper#29]
I have this error and dont know how to fix it.
Traceback (most recent call last):
  File "main.py", line 452, in <module>
    main()
  File "main.py", line 440, in main
    go_to_next_page()
  File "main.py", line 317, in go_to_next_page
    next_ = browser.find_element_by_xpath(".//li[@class='pagination__PaginationStyle__next']/a")
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":".//li[@class='pagination__PaginationStyle__next']/a"}
  (Session info: headless chrome=77.0.3865.90)

**Comment by madhuqmar** [comment]
i'm getting the same error

**Comment by sachinchaturvedi93** [comment]
`    next_ = browser.find_element_by_class_name(
        'pagination__PaginationStyle__next').find_element_by_tag_name('a')
    browser.get(next_.get_attribute('href'))`

**Comment by nikhiljsk** [comment]
This guy updated the code. Check this repo. It works

https://github.com/iopsych/glassdoor-review-scraper
