### ISSUE TITLE
Error when running Example 1. Please help!

### ISSUE THREAD

**Issue by supersylvia215** [MatthewChatham/glassdoor-review-scraper#44]
Hi, I tried to run example 1 but returned with error. Could you please help? Many thanks! 
Please see below.

----
C:\Users\liusi\Desktop\glassdoor-review-scraper-master-matt>python main.py --headless --url "https://www.glassdoor.co.uk/Overview/Working-at-Well
s-Fargo-EI_IE8876.11,22.htm" --limit 1000 -f wells_fargo_reviews.csv
2020-07-02 20:08:41,025 INFO 416    :main.py(4100) - Configuring browser

DevTools listening on ws://127.0.0.1:51703/devtools/browser/37f604c9-f5f4-4325-ac1d-a1b5514cff80
2020-07-02 20:08:43,379 INFO 458    :main.py(4100) - Scraping up to 1000 reviews.
2020-07-02 20:08:43,397 INFO 395    :main.py(4100) - Signing in to XXXXX@gmail.com
Traceback (most recent call last):
  File "main.py", line 500, in <module>
    main()
  File "main.py", line 462, in main
    sign_in()
  File "main.py", line 408, in sign_in
    submit_btn.click()
  File "C:\Users\liusi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\liusi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execut
e
    return self._parent.execute(command, params)
  File "C:\Users\liusi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\liusi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check
_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="gd-ui-button minWidthBtn
css-1sdotxz" type="submit" name="submit">...</button> is not clickable at point (387, 488). Other element would receive the click: <p id="onetrus
t-policy-text">...</p>
  (Session info: headless chrome=83.0.4103.116)

**Comment by kingwongf** [comment]
Same issue here,

`
Traceback (most recent call last):
  File "main.py", line 500, in <module>
    main()
  File "main.py", line 462, in main
    sign_in()
  File "main.py", line 408, in sign_in
    submit_btn.click()
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/kingf.wong/.conda/envs/FinanceML/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="gd-ui-button minWidthBtn css-1sdotxz" type="submit" name="submit">...</button> is not clickable at point (400, 488). Other element would receive the click: <p id="onetrust-policy-text">...</p>
  (Session info: headless chrome=85.0.4183.102)

`

**Comment by DustinTheGreat** [comment]
pretty sure predefining window size would fix it. Could you try adding the configurations, it should look similar to something like this. Let me know if this worked so I can make a pull request.


    chromeOptions: {
        args: ['headless', 'window-size=1920,1080']
    }
