### ISSUE TITLE
Credentials error despite passing them?

### ISSUE THREAD

**Issue by rocnoa** [MatthewChatham/glassdoor-review-scraper#54]
I set up everything as per your instructions but since there is no example of the JSON file attached I am passing username and password with --username and --password. Note - the password contains special characters - "*" and "#". I still get this error:

Traceback (most recent call last):
  File "/Users/XXX/Documents/GitHub/glassdoor-review-scraper/main.py", line 88, in <module>
    with open('secret.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'secret.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXX/Documents/GitHub/glassdoor-review-scraper/main.py", line 97, in <module>
    raise Exception(msg)
Exception: Please provide Glassdoor credentials.        Credentials can be provided as a secret.json file in the working        directory, or passed at the command line using the --username and        --password flags.

Can you provide a sample JSON or feedback of any sort?

Thank you!

Here is the command I used:
python3 main.py --headless --url "https://www.glassdoor.ca/Reviews/XXX.htm" -f test.csv --headless --username person@email.com --password XXXX -l 260

**Comment by harshu729** [comment]
Create a txt file and add this content to it
{
  "username": "email_id",
  "password": "your_pass"
}
Then go to files and Save As JSON and rename the file to secret.
