### ISSUE TITLE
Chrome web driver arg chrome_options is deprecated

### ISSUE THREAD

**Issue by yihaozhadan** [MatthewChatham/glassdoor-review-scraper#9]
Chrome web driver arg **chrome_options** is deprecated. Please use "option" instead. For example, in main.py line 382, change to
```python
browser = wd.Chrome(options=chrome_options)
```
Here is the reference [webdriver.py](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/chrome/webdriver.py).

By the way, may I be a contributor to your repository?

**Comment by mchatham-fk** [comment]
Hey @yihaozhadan, thanks for the suggestion! If you fork the repo, you can make a PR from your fork. Thanks!

**Comment by liudi1025** [comment]
Hi, after changing 'chrome_options' into 'options', I still encounter the problem with error message: "The application was unable to start correctly(0xc000007b)." I followed all the steps in the README.md. However, still not working here.

**Comment by yihaozhadan** [comment]
@liudi1025 
Did you download [ChromeDirver](http://chromedriver.chromium.org/)? When you check out the repository. It requires to put chromedriver.exe and your Glassdoor credential file under the root folder. The structure looks like:
```
- chromedriver.exe
- main.py
- README.md
- requirements.txt
- schema.py
- secret.json
```

**Comment by liudi1025** [comment]
Yes, I did include the ChromeDriver.

**Comment by liudi1025** [comment]
Now I am getting the error message as:

2019-04-21 13:30:18,740 INFO 377    :main.py(19096) - Configuring browser
Traceback (most recent call last):
  File "main.py", line 411, in <module>
    browser = get_browser()
  File "main.py", line 382, in get_browser
    browser = wd.Chrome(options=chrome_options)
  File "C:\Users\liudi\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "C:\Users\liudi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\liudi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\liudi\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\liudi\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\liudi\AppData\Local\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Windows NT 10.0.17134 x86_64)

**Comment by liudi1025** [comment]
I got what happened here: there are two chrome.exe in my computer and the path direct me to the crashed version of chrome...
Thanks!@yihaozhadan

**Comment by yihaozhadan** [comment]
@liudi1025 
It's good to hear that. No problem.

**Comment by MatthewChatham** [comment]
@yihaozhadan can you please make a PR to update this? Thanks!

**Comment by yihaozhadan** [comment]
@MatthewChatham Created [pull request](https://github.com/MatthewChatham/glassdoor-review-scraper/pull/11).

**Comment by wenxin-lab** [comment]
Hi, I tried the code, and got this error:

2019-09-29 15:41:04,215 INFO 377    :main.py(10918) - Configuring browser
Traceback (most recent call last):
  File "main.py", line 412, in <module>
    browser = get_browser()
  File "main.py", line 382, in get_browser
    browser = wd.Chrome(options=chrome_options)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/var/pyenv/versions/anaconda3-2019.03/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 78

But my chrome version is 78, so I have no idea how to fix it...
